name: ChunkFreezer
version: '1.0.2-b2'
main: com.heonezen.chunkfreezer.ChunkFreezerPlugin
api-version: '1.21'
folia-supported: true
authors:
 - HeOneZen
description: Automatically freezes overloaded chunks.
website: https://github.com/mishakorzik
permissions:
  chunkfreezer.admin:
    description: Access to ChunkFreezer commands.
    default: op
  chunkfreezer.bypass:
    description: Bypasses all frozen chunk barriers (no command access).
    default: false
commands:
  chunk:
    description: ChunkFreezer management commands.
    usage: /chunk <go|list|reload>
    permission: chunkfreezer.admin
