name: ChunkFreezer
version: 1.0.0
main: com.heonezen.chunkfreezer.ChunkFreezerPlugin
api-version: "1.21"
folia-supported: true
authors:
 - HeOneZen
description: Automatically freezes overloaded chunks on Folia (1.21.8)
website: https://github.com/mishakorzik
